/* Parser type: LL1 with Backtracking */
RIB
        ::= Preamble EOF
Preamble
        ::= Command+
Command    
        ::= StructuralHint WS* NL?
StructuralHint
        ::= ( ('##RenderMan' WS Name) | ('##Scene' WS Name) | ('##Creator' WS Name) | 
              ('##CreationDate' WS DateTime) | ('##For' WS Name)|  ('##Frames' WS Number) | 
              ('##Textures' WS Texture+) | ('##Shaders' WS Shader+) | ('##CapabilitiesNeeded' WS Feature+) )
Shader
        ::= NMToken ','? WS?
Texture
        ::= NMToken ','? WS?
Feature
        ::= NMToken ','? WS?
          
<?TOKENS?>

Name    ::= ( [^#x000A#x000D#x000C\"] | WS | NONASCII | ESCAPE )*
Number
        ::= [0-9]+
DateTime
        ::= ( [^#x000A#x000D#x000C\"] | WS | NONASCII | ESCAPE )*
NMToken
        ::= [a-zA-Z]*

STRING  
        ::= ( STRING1 | STRING2 )
STRING1 
        ::= '"' ( [^#x000A#x000D#x000C\"] | '\' | NONASCII | ESCAPE )* '"'
STRING2 
        ::= "'" ( [^#x000A#x000D#x000C\'] | '\' | NONASCII | ESCAPE )* "'"
WS      ::= #x0020
NL      ::= #x000A
          | #x000D #x000A
          | #x000D
          | #x000C
NONASCII 
        ::= [^#x0000-#x007F]
ESCAPE   
        ::= UNICODE
           | '\' [^0-9a-f#x000A#x000D#x000C]
UNICODE  
        ::= '\' ONE-TO-SIX-HEX-DIGITS ( #x000D #x000A | [ #x000A#x000D#x0009#x000C] )?
ONE-TO-SIX-HEX-DIGITS
        ::= [0-9a-f]
          | [0-9a-f] [0-9a-f]
          | [0-9a-f] [0-9a-f] [0-9a-f]
          | [0-9a-f] [0-9a-f] [0-9a-f] [0-9a-f]
          | [0-9a-f] [0-9a-f] [0-9a-f] [0-9a-f] [0-9a-f]
          | [0-9a-f] [0-9a-f] [0-9a-f] [0-9a-f] [0-9a-f] [0-9a-f]
EOF
        ::= #x0000